package com.softech.ls360.lcms.contentbuilder.model;



import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;

/**
 * Course generated by hbm2java
 */

@javax.persistence.Entity
@NamedQueries(value={
		@NamedQuery(name="AssetGroupById", query="select ag from AssetGroup ag where ag.id = :id")
})


public class AssetGroup implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * 
	 */
	@Id
	 private long ID;
	private String PARENT_AG_ID;
	private String NAME;	
	private String DESCRIPTION;	
	private String KEYWORDS;
	private String CONTENTOWNER_ID;	
	private String ASSETGROUP_GUID;	
	private String CreateUserId;
	private String ROOT_ID;
	private String COURSE_ID;


	public AssetGroup() {
	}
	
	public AssetGroup (int ID, String PARENT_AG_ID, String NAME, String  DESCRIPTION, String KEYWORDS
			, String CONTENTOWNER_ID,String ASSETGROUP_GUID, String CreateUserId, String ROOT_ID, String COURSE_ID)
	{
		 this.ID = ID;
		 this.PARENT_AG_ID=	PARENT_AG_ID;
		 this.NAME	=NAME;
		 this.DESCRIPTION=	DESCRIPTION;
		 this.KEYWORDS	=KEYWORDS;
		 this.CONTENTOWNER_ID=	CONTENTOWNER_ID;
		 this.ASSETGROUP_GUID=	ASSETGROUP_GUID;
		 this.CreateUserId	=CreateUserId;
		 this.ROOT_ID	=ROOT_ID;
		 this.COURSE_ID=COURSE_ID;
		
	}

	public long getID() {
		return ID;
	}

	public void setID(long iD) {
		ID = iD;
	}

	public String getPARENT_AG_ID() {
		return PARENT_AG_ID;
	}

	public void setPARENT_AG_ID(String pARENT_AG_ID) {
		PARENT_AG_ID = pARENT_AG_ID;
	}

	public String getNAME() {
		return NAME;
	}

	public void setNAME(String nAME) {
		NAME = nAME;
	}

	public String getDESCRIPTION() {
		return DESCRIPTION;
	}

	public void setDESCRIPTION(String dESCRIPTION) {
		DESCRIPTION = dESCRIPTION;
	}

	public String getKEYWORDS() {
		return KEYWORDS;
	}

	public void setKEYWORDS(String kEYWORDS) {
		KEYWORDS = kEYWORDS;
	}

	public String getCONTENTOWNER_ID() {
		return CONTENTOWNER_ID;
	}

	public void setCONTENTOWNER_ID(String cONTENTOWNER_ID) {
		CONTENTOWNER_ID = cONTENTOWNER_ID;
	}

	public String getASSETGROUP_GUID() {
		return ASSETGROUP_GUID;
	}

	public void setASSETGROUP_GUID(String aSSETGROUP_GUID) {
		ASSETGROUP_GUID = aSSETGROUP_GUID;
	}

	public String getCreateUserId() {
		return CreateUserId;
	}

	public void setCreateUserId(String createUserId) {
		CreateUserId = createUserId;
	}

	public String getROOT_ID() {
		return ROOT_ID;
	}

	public void setROOT_ID(String rOOT_ID) {
		ROOT_ID = rOOT_ID;
	}

	public String getCOURSE_ID() {
		return COURSE_ID;
	}

	public void setCOURSE_ID(String cOURSE_ID) {
		COURSE_ID = cOURSE_ID;
	}
	

	
	
	
}
