package com.softech.ls360.lcms.contentbuilder.model;

// Generated Jun 4, 2014 1:40:35 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Transient;
/**
 * Course generated by hbm2java
 */
//select crs.id, crs.name, crs.description, crs.language_id, crs.duration, crs.keywords from Course crs where crs.id = :id
//
// @Entity
@javax.persistence.Entity
@NamedQueries(value={
		@NamedQuery(name="Course.CouseByID", query="select crs from Course crs where crs.id = :id")
})

/*@NamedQueries(value={
		@NamedQuery(name="Course.CouseByID", query="call spS_NamedQuery(?)")
})*/
public class Course implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * 
	 */
	@Id
	@javax.persistence.TableGenerator(name = "COURSE_ID", table = "VU360_SEQ", pkColumnName = "TABLE_NAME", valueColumnName = "NEXT_ID", pkColumnValue = "COURSE", allocationSize = 20)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "COURSE_ID")
	private int id;
	private String version;

	private String name;
	private String coursestatus;
	private Boolean retiredtf;
	private String keywords;

	private Integer  branding_id;

	private Integer  language_id;
	
	private Integer  contentowner_id;
	
	private Integer  businessunit_id;
	private String businessunit_name;

	private int courseconfigurationtemplate_id;
	
		
	@Transient
	private Boolean ratingTF;
	
	@Transient
	private BigDecimal rating; 
	// QUICK_BUILD_COURSETYPE this value would be set based on Document Type being uploaded
	@Transient
	private Integer  quick_build_coursetype;
	
	@Transient	
	private String publishstatus;
	
	@Transient	
	private String coursegroup;
	
	@Transient
	private List<Lesson> lessonList = null;
	
	@Transient
	private int authorId;
	
	public int getAuthorId() {
		return authorId;
	}

	public void setAuthorId(int authorId) {
		this.authorId = authorId;
	}

	public List<Lesson> getLessonList() {
		return lessonList;
	}

	public void setLessonList(List<Lesson> lessonList) {
		this.lessonList = lessonList;
	}
	
	public boolean addLesson(Lesson lesson) {
		
		if(lesson == null){
			return false;
		}
		if(this.lessonList == null || lessonList.size() == 0){
			this.lessonList = new ArrayList<Lesson>();
		}
		return this.lessonList.add(lesson);
	}

	public String getPublishstatus() {
		return publishstatus;
	}

	public void setPublishstatus(String publishstatus) {
		this.publishstatus = publishstatus;
	}

	public String getCoursegroup() {
		return coursegroup;
	}

	public void setCoursegroup(String coursegroup) {
		this.coursegroup = coursegroup;
	}

	public void setCourseconfigurationtemplate_id(int courseconfigurationtemplate_id) {
		this.courseconfigurationtemplate_id = courseconfigurationtemplate_id;
	}

	@Transient
	private String filename; 



	public String getFilename() {
		return filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	public Integer   getQuick_build_coursetype() {
		return quick_build_coursetype;
	}

	public void setQuick_build_coursetype(Integer  quick_build_coursetype) {
		this.quick_build_coursetype = quick_build_coursetype;
	}

	public Integer  getCourseconfigurationtemplate_id() {
		return courseconfigurationtemplate_id;
	}

	public void setCourseconfigurationtemplate_id(Integer  courseconfigurationtemplate_id) {
		this.courseconfigurationtemplate_id = courseconfigurationtemplate_id;
	}

	private String courseType;
	private String code;
	private String description;
	private String guid;
	private String courseguide;

	private String deliverymethod;
	private String topicscovered;
	private String quizinfo;
	private String finalexaminfo;

	private String endofcourseinstructions;
	private String additionalmaterials;
	private String subjectmatterexpertinfo;
	private BigDecimal msrp;
	private String learningobjectives;
	private Boolean publishedonvu;
	private Boolean publishedonstorefront;
	private String bussinesskey;
	private BigDecimal productprice;
	private String currency;
	private Long approvedcoursehours;
	private BigDecimal ceus;

	private String approvalnumber;
	private String imageofcourse;

	private String regulatingbody;
	private String assesments;
	private String courseid;
	private String coursemediatype;
	private Integer tos;
	private String link;
	private String coursecategory;
	private String credithour;
	private BigDecimal wholeSalePrice;
	private BigDecimal royaltyAmount;
	private String royaltyType;
	private String reportedscormversion;
	private String coursevendor;

	private Date createdDate;
	private Long createUserId;
	private Date lastUpdatedDate;
	private Long lastUpdateUser;

	private String shortname;
	private String duration;

	private String royaltyPartner;
	private BigDecimal lowestprice;
	private Date courseexpiration;
	private Date lastpublisheddate;

	private Date homeworkassignmentduedate;
	private String homeworkassignmentgradingmethod;
	private BigDecimal homeworkassignmentmasteryscore;
	private String instructorconnecttype;
	private String instructorconnectmeetingid;
	private String instructorconnectmeetingpasscode;
	private String instructorconnectemailaddress;

	private BigDecimal directroyaltyamount;
	private BigDecimal directroyaltypercentage;
	private BigDecimal varroyaltyamount;
	private BigDecimal varroyaltypercentage;

	private String coursecreator;
	private String courselevel;

	private Boolean enablednoteligibleformobiletablet;
	private Boolean enablednoteligibleforsubscription;
	private Boolean enablednoteligibleforvarresale;
	private Boolean enablednoteligibleforscorm;
	private Boolean enablednoteligibleforaicc;
	private Boolean enabledrequiresshippableitems;
	private Boolean enabledrequiresreportingtoregulators;
	private Boolean enabledthirdpartycourse;

	private Boolean enabledadditionalinforoncourseapproval;
	private String lastModifiedDate = null;
	
	public Course() {
	}
	
	public Course (int id, String name, String description, Integer  language_id, String duration, String keywords)
	{
		this.id = id;
		this.name = name;
		this.description = description;
		this.language_id = language_id;
		this.duration = duration;
		this.keywords = keywords;
	}
	// SELECT COURSE SP
	// abandoned this approach, will have to try this sometime later
	/*public Course (int id, String name, String courseStatus, Integer  Version, String Keywords, Integer BrandingID,  Integer contentOwner_ID, String courseType, String code, String descripting, String courseGuid, Boolean retiredTF, 
			String courseGUID, Integer AssetID, String topicsCovered, String quizInfo, String deliveryMethod, String finalExamInfo, String COURSEPREREQ, String EOCINSTRUCTIONS)
	{
		this.id = id;
		this.name = name;
		this.description = description;
		this.language_id = language_id;
		this.duration = duration;
		this.keywords = keywords;
	}*/


	public Course(Course course, String name, String coursestatus) {
		this.name = name;
		this.coursestatus =  coursestatus;
	}

	public Course(String name, String coursestatus, Boolean retiredtf,
			String keywords, String courseType, String code,
			String description, String guid, String courseguide,
			String deliverymethod, String topicscovered, String quizinfo,
			String finalexaminfo, String endofcourseinstructions,
			String additionalmaterials, String subjectmatterexpertinfo,
			BigDecimal msrp, String learningobjectives, Boolean publishedonvu,
			Boolean publishedonstorefront, String bussinesskey,
			BigDecimal productprice, String currency, Long approvedcoursehours,
			BigDecimal ceus, String approvalnumber, String imageofcourse,
			String regulatingbody, String assesments, String courseid,
			String coursemediatype, Integer tos, String link,
			String coursecategory, String credithour,
			BigDecimal wholeSalePrice, BigDecimal royaltyAmount,
			String royaltyType, String reportedscormversion,
			String coursevendor, Date createdDate, Long createUserId,
			Date lastUpdatedDate, Long lastUpdateUser, String shortname,
			String duration, String royaltyPartner, BigDecimal lowestprice,
			Date courseexpiration, Date lastpublisheddate,

			Date homeworkassignmentduedate,
			String homeworkassignmentgradingmethod,
			BigDecimal homeworkassignmentmasteryscore,
			String instructorconnecttype, String instructorconnectmeetingid,
			String instructorconnectmeetingpasscode,
			String instructorconnectemailaddress,
			BigDecimal directroyaltyamount, BigDecimal directroyaltypercentage,
			BigDecimal varroyaltyamount, BigDecimal varroyaltypercentage,
			String coursecreator, String courselevel,

			Boolean enablednoteligibleformobiletablet,
			Boolean enablednoteligibleforsubscription,
			Boolean enablednoteligibleforvarresale,
			Boolean enablednoteligibleforscorm,
			Boolean enablednoteligibleforaicc,
			Boolean enabledrequiresshippableitems,
			Boolean enabledrequiresreportingtoregulators,
			Boolean enabledthirdpartycourse,

			Boolean enabledadditionalinforoncourseapproval,
			Integer  branding_id,
			Integer  language_id,			
			Integer  contentowner_id,			
			Integer  businessunit_id,
			String businessunit_name, 
			Integer  courseconfigurationtemplate_id,
			String coursegroup, String  publishstatus) {

		this.name = name;
		this.coursestatus =  coursestatus;
		this.retiredtf = retiredtf;
		this.keywords = keywords;

		this.courseType = courseType;
		this.code = code;
		this.description = description;
		this.guid = guid;
		this.courseguide = courseguide;

		this.deliverymethod = deliverymethod;
		this.topicscovered = topicscovered;
		this.quizinfo = quizinfo;
		this.finalexaminfo = finalexaminfo;

		this.endofcourseinstructions = endofcourseinstructions;
		this.additionalmaterials = additionalmaterials;
		this.subjectmatterexpertinfo = subjectmatterexpertinfo;
		this.msrp = msrp;
		this.learningobjectives = learningobjectives;
		this.publishedonvu = publishedonvu;
		this.publishedonstorefront = publishedonstorefront;
		this.bussinesskey = bussinesskey;
		this.productprice = productprice;
		this.currency = currency;
		this.approvedcoursehours = approvedcoursehours;
		this.ceus = ceus;

		this.approvalnumber = approvalnumber;
		this.imageofcourse = imageofcourse;

		this.regulatingbody = regulatingbody;
		this.assesments = assesments;
		this.courseid = courseid;
		this.coursemediatype = coursemediatype;
		this.tos = tos;
		this.link = link;
		this.coursecategory = coursecategory;
		this.credithour = credithour;
		this.wholeSalePrice = wholeSalePrice;
		this.royaltyAmount = royaltyAmount;
		this.royaltyType = royaltyType;
		this.reportedscormversion = reportedscormversion;
		this.coursevendor = coursevendor;

		this.createdDate = createdDate;
		this.createUserId = createUserId;
		this.lastUpdatedDate = lastUpdatedDate;
		this.lastUpdateUser = lastUpdateUser;

		this.shortname = shortname;
		this.duration = duration;

		this.royaltyPartner = royaltyPartner;
		this.lowestprice = lowestprice;
		this.courseexpiration = courseexpiration;
		this.lastpublisheddate = lastpublisheddate;

		this.homeworkassignmentduedate = homeworkassignmentduedate;
		this.homeworkassignmentgradingmethod = homeworkassignmentgradingmethod;
		this.homeworkassignmentmasteryscore = homeworkassignmentmasteryscore;
		this.instructorconnecttype = instructorconnecttype;
		this.instructorconnectmeetingid = instructorconnectmeetingid;
		this.instructorconnectmeetingpasscode = instructorconnectmeetingpasscode;
		this.instructorconnectemailaddress = instructorconnectemailaddress;

		this.directroyaltyamount = directroyaltyamount;
		this.directroyaltypercentage = directroyaltypercentage;
		this.varroyaltyamount = varroyaltyamount;
		this.varroyaltypercentage = varroyaltypercentage;

		this.coursecreator = coursecreator;
		this.courselevel = courselevel;

		this.enablednoteligibleformobiletablet = enablednoteligibleformobiletablet;
		this.enablednoteligibleforsubscription = enablednoteligibleforsubscription;
		this.enablednoteligibleforvarresale = enablednoteligibleforvarresale;
		this.enablednoteligibleforscorm = enablednoteligibleforscorm;
		this.enablednoteligibleforaicc = enablednoteligibleforaicc;
		this.enabledrequiresshippableitems = enabledrequiresshippableitems;
		this.enabledrequiresreportingtoregulators = enabledrequiresreportingtoregulators;
		this.enabledthirdpartycourse = enabledthirdpartycourse;

		this.enabledadditionalinforoncourseapproval = enabledadditionalinforoncourseapproval;
		this.branding_id = branding_id;
		this.language_id = language_id;			
		this.contentowner_id = contentowner_id;
		this.businessunit_id = businessunit_id;
		this.businessunit_name = businessunit_name; 
		this.courseconfigurationtemplate_id = courseconfigurationtemplate_id;
		this.coursegroup = coursegroup; 
		this.publishstatus = publishstatus;

	}
	
	public Integer  getBusinessunit_id() {
		return businessunit_id;
	}

	public void setBusinessunit_id(Integer  businessunit_id) {
		this.businessunit_id = businessunit_id;
	}
	
	public Integer  getContentowner_id() {
		return contentowner_id;
	}

	public void setContentowner_id(Integer  contentowner_id) {
		this.contentowner_id = contentowner_id;
	}
	
	public Integer  getLanguage_id() {
		return language_id;
	}

	public void setLanguage_id(Integer  language_id) {
		this.language_id = language_id;
	}
	
	public Integer  getBranding_id() {
		return branding_id;
	}

	public void setBranding_id(Integer  branding_id) {
		this.branding_id = branding_id;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	
	public String getBusinessunit_name() {
		return businessunit_name;
	}

	public void setBusinessunit_name(String businessunit_name) {
		this.businessunit_name = businessunit_name;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCoursestatus() {
		return coursestatus;
	}

	public void setCoursestatus(String coursestatus) {
		this.coursestatus = coursestatus;
	}

	public Boolean getRetiredtf() {
		return this.retiredtf;
	}

	public void setRetiredtf(Boolean retiredtf) {
		this.retiredtf = retiredtf;
	}

	public String getKeywords() {
		return this.keywords;
	}

	public void setKeywords(String keywords) {
		this.keywords = keywords;
	}

	public String getCourseType() {
		return courseType;
	}

	public void setCourseType(String courseType) {
		this.courseType = courseType;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	public String getCourseguide() {
		return this.courseguide;
	}

	public void setCourseguide(String courseguide) {
		this.courseguide = courseguide;
	}

	public String getDeliverymethod() {
		return this.deliverymethod;
	}

	public void setDeliverymethod(String deliverymethod) {
		this.deliverymethod = deliverymethod;
	}

	public String getTopicscovered() {
		return this.topicscovered;
	}

	public void setTopicscovered(String topicscovered) {
		this.topicscovered = topicscovered;
	}

	public String getQuizinfo() {
		return this.quizinfo;
	}

	public void setQuizinfo(String quizinfo) {
		this.quizinfo = quizinfo;
	}

	public String getFinalexaminfo() {
		return this.finalexaminfo;
	}

	public void setFinalexaminfo(String finalexaminfo) {
		this.finalexaminfo = finalexaminfo;
	}

	public String getEndofcourseinstructions() {
		return this.endofcourseinstructions;
	}

	public void setEndofcourseinstructions(String endofcourseinstructions) {
		this.endofcourseinstructions = endofcourseinstructions;
	}

	public String getAdditionalmaterials() {
		return this.additionalmaterials;
	}

	public void setAdditionalmaterials(String additionalmaterials) {
		this.additionalmaterials = additionalmaterials;
	}

	public String getSubjectmatterexpertinfo() {
		return this.subjectmatterexpertinfo;
	}

	public void setSubjectmatterexpertinfo(String subjectmatterexpertinfo) {
		this.subjectmatterexpertinfo = subjectmatterexpertinfo;
	}

	public BigDecimal getMsrp() {
		return this.msrp;
	}

	public void setMsrp(BigDecimal msrp) {
		this.msrp = msrp;
	}

	public String getLearningobjectives() {
		return this.learningobjectives;
	}

	public void setLearningobjectives(String learningobjectives) {
		this.learningobjectives = learningobjectives;
	}

	public Boolean getPublishedonvu() {
		return this.publishedonvu;
	}

	public void setPublishedonvu(Boolean publishedonvu) {
		this.publishedonvu = publishedonvu;
	}

	public Boolean getPublishedonstorefront() {
		return this.publishedonstorefront;
	}

	public void setPublishedonstorefront(Boolean publishedonstorefront) {
		this.publishedonstorefront = publishedonstorefront;
	}

	public String getBussinesskey() {
		return this.bussinesskey;
	}

	public void setBussinesskey(String bussinesskey) {
		this.bussinesskey = bussinesskey;
	}

	public BigDecimal getProductprice() {
		return this.productprice;
	}

	public void setProductprice(BigDecimal productprice) {
		this.productprice = productprice;
	}

	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	public Long getApprovedcoursehours() {
		return this.approvedcoursehours;
	}

	public void setApprovedcoursehours(Long approvedcoursehours) {
		this.approvedcoursehours = approvedcoursehours;
	}

	public BigDecimal getCeus() {
		return this.ceus;
	}

	public void setCeus(BigDecimal ceus) {
		this.ceus = ceus;
	}

	public String getApprovalnumber() {
		return this.approvalnumber;
	}

	public void setApprovalnumber(String approvalnumber) {
		this.approvalnumber = approvalnumber;
	}

	public String getImageofcourse() {
		return this.imageofcourse;
	}

	public void setImageofcourse(String imageofcourse) {
		this.imageofcourse = imageofcourse;
	}

	public String getRegulatingbody() {
		return this.regulatingbody;
	}

	public void setRegulatingbody(String regulatingbody) {
		this.regulatingbody = regulatingbody;
	}

	public String getAssesments() {
		return this.assesments;
	}

	public void setAssesments(String assesments) {
		this.assesments = assesments;
	}

	public String getCourseid() {
		return this.courseid;
	}

	public void setCourseid(String courseid) {
		this.courseid = courseid;
	}

	public String getCoursemediatype() {
		return this.coursemediatype;
	}

	public void setCoursemediatype(String coursemediatype) {
		this.coursemediatype = coursemediatype;
	}

	public Integer getTos() {
		return this.tos;
	}

	public void setTos(Integer tos) {
		this.tos = tos;
	}

	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	public String getCoursecategory() {
		return this.coursecategory;
	}

	public void setCoursecategory(String coursecategory) {
		this.coursecategory = coursecategory;
	}

	public String getCredithour() {
		return this.credithour;
	}

	public void setCredithour(String credithour) {
		this.credithour = credithour;
	}

	public BigDecimal getWholeSalePrice() {
		return this.wholeSalePrice;
	}

	public void setWholeSalePrice(BigDecimal wholeSalePrice) {
		this.wholeSalePrice = wholeSalePrice;
	}

	public BigDecimal getRoyaltyAmount() {
		return this.royaltyAmount;
	}

	public void setRoyaltyAmount(BigDecimal royaltyAmount) {
		this.royaltyAmount = royaltyAmount;
	}

	public String getRoyaltyType() {
		return this.royaltyType;
	}

	public void setRoyaltyType(String royaltyType) {
		this.royaltyType = royaltyType;
	}

	public String getReportedscormversion() {
		return this.reportedscormversion;
	}

	public void setReportedscormversion(String reportedscormversion) {
		this.reportedscormversion = reportedscormversion;
	}

	public String getCoursevendor() {
		return this.coursevendor;
	}

	public void setCoursevendor(String coursevendor) {
		this.coursevendor = coursevendor;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Long getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(Long createUserId) {
		this.createUserId = createUserId;
	}

	public Date getLastUpdatedDate() {
		return this.lastUpdatedDate;
	}

	public void setLastUpdatedDate(Date lastUpdatedDate) {
		this.lastUpdatedDate = lastUpdatedDate;
	}

	public Long getLastUpdateUser() {
		return this.lastUpdateUser;
	}

	public void setLastUpdateUser(Long lastUpdateUser) {
		this.lastUpdateUser = lastUpdateUser;
	}

	public String getShortname() {
		return this.shortname;
	}

	public void setShortname(String shortname) {
		this.shortname = shortname;
	}

	public String getDuration() {
		return this.duration;
	}

	public void setDuration(String duration) {
		this.duration = duration;
	}

	public String getRoyaltyPartner() {
		return this.royaltyPartner;
	}

	public void setRoyaltyPartner(String royaltyPartner) {
		this.royaltyPartner = royaltyPartner;
	}

	public BigDecimal getLowestprice() {
		return this.lowestprice;
	}

	public void setLowestprice(BigDecimal lowestprice) {
		this.lowestprice = lowestprice;
	}

	public Date getCourseexpiration() {
		return this.courseexpiration;
	}

	public void setCourseexpiration(Date courseexpiration) {
		this.courseexpiration = courseexpiration;
	}

	public Date getLastpublisheddate() {
		return this.lastpublisheddate;
	}

	public void setLastpublisheddate(Date lastpublisheddate) {
		this.lastpublisheddate = lastpublisheddate;
	}

	public Date getHomeworkassignmentduedate() {
		return this.homeworkassignmentduedate;
	}

	public void setHomeworkassignmentduedate(Date homeworkassignmentduedate) {
		this.homeworkassignmentduedate = homeworkassignmentduedate;
	}

	public String getHomeworkassignmentgradingmethod() {
		return this.homeworkassignmentgradingmethod;
	}

	public void setHomeworkassignmentgradingmethod(
			String homeworkassignmentgradingmethod) {
		this.homeworkassignmentgradingmethod = homeworkassignmentgradingmethod;
	}

	public BigDecimal getHomeworkassignmentmasteryscore() {
		return this.homeworkassignmentmasteryscore;
	}

	public void setHomeworkassignmentmasteryscore(
			BigDecimal homeworkassignmentmasteryscore) {
		this.homeworkassignmentmasteryscore = homeworkassignmentmasteryscore;
	}

	public String getInstructorconnecttype() {
		return this.instructorconnecttype;
	}

	public void setInstructorconnecttype(String instructorconnecttype) {
		this.instructorconnecttype = instructorconnecttype;
	}

	public String getInstructorconnectmeetingid() {
		return this.instructorconnectmeetingid;
	}

	public void setInstructorconnectmeetingid(String instructorconnectmeetingid) {
		this.instructorconnectmeetingid = instructorconnectmeetingid;
	}

	public String getInstructorconnectmeetingpasscode() {
		return this.instructorconnectmeetingpasscode;
	}

	public void setInstructorconnectmeetingpasscode(
			String instructorconnectmeetingpasscode) {
		this.instructorconnectmeetingpasscode = instructorconnectmeetingpasscode;
	}

	public String getInstructorconnectemailaddress() {
		return this.instructorconnectemailaddress;
	}

	public void setInstructorconnectemailaddress(
			String instructorconnectemailaddress) {
		this.instructorconnectemailaddress = instructorconnectemailaddress;
	}

	public BigDecimal getDirectroyaltyamount() {
		return this.directroyaltyamount;
	}

	public void setDirectroyaltyamount(BigDecimal directroyaltyamount) {
		this.directroyaltyamount = directroyaltyamount;
	}

	public BigDecimal getDirectroyaltypercentage() {
		return this.directroyaltypercentage;
	}

	public void setDirectroyaltypercentage(BigDecimal directroyaltypercentage) {
		this.directroyaltypercentage = directroyaltypercentage;
	}

	public BigDecimal getVarroyaltyamount() {
		return this.varroyaltyamount;
	}

	public void setVarroyaltyamount(BigDecimal varroyaltyamount) {
		this.varroyaltyamount = varroyaltyamount;
	}

	public BigDecimal getVarroyaltypercentage() {
		return this.varroyaltypercentage;
	}

	public void setVarroyaltypercentage(BigDecimal varroyaltypercentage) {
		this.varroyaltypercentage = varroyaltypercentage;
	}

	public String getCoursecreator() {
		return this.coursecreator;
	}

	public void setCoursecreator(String coursecreator) {
		this.coursecreator = coursecreator;
	}

	public String getCourselevel() {
		return this.courselevel;
	}

	public void setCourselevel(String courselevel) {
		this.courselevel = courselevel;
	}

	public Boolean getEnablednoteligibleformobiletablet() {
		return this.enablednoteligibleformobiletablet;
	}

	public void setEnablednoteligibleformobiletablet(
			Boolean enablednoteligibleformobiletablet) {
		this.enablednoteligibleformobiletablet = enablednoteligibleformobiletablet;
	}

	public Boolean getEnablednoteligibleforsubscription() {
		return this.enablednoteligibleforsubscription;
	}

	public void setEnablednoteligibleforsubscription(
			Boolean enablednoteligibleforsubscription) {
		this.enablednoteligibleforsubscription = enablednoteligibleforsubscription;
	}

	public Boolean getEnablednoteligibleforvarresale() {
		return this.enablednoteligibleforvarresale;
	}

	public void setEnablednoteligibleforvarresale(
			Boolean enablednoteligibleforvarresale) {
		this.enablednoteligibleforvarresale = enablednoteligibleforvarresale;
	}

	public Boolean getEnablednoteligibleforscorm() {
		return this.enablednoteligibleforscorm;
	}

	public void setEnablednoteligibleforscorm(Boolean enablednoteligibleforscorm) {
		this.enablednoteligibleforscorm = enablednoteligibleforscorm;
	}

	public Boolean getEnablednoteligibleforaicc() {
		return this.enablednoteligibleforaicc;
	}

	public void setEnablednoteligibleforaicc(Boolean enablednoteligibleforaicc) {
		this.enablednoteligibleforaicc = enablednoteligibleforaicc;
	}

	public Boolean getEnabledrequiresshippableitems() {
		return this.enabledrequiresshippableitems;
	}

	public void setEnabledrequiresshippableitems(
			Boolean enabledrequiresshippableitems) {
		this.enabledrequiresshippableitems = enabledrequiresshippableitems;
	}

	public Boolean getEnabledrequiresreportingtoregulators() {
		return this.enabledrequiresreportingtoregulators;
	}

	public void setEnabledrequiresreportingtoregulators(
			Boolean enabledrequiresreportingtoregulators) {
		this.enabledrequiresreportingtoregulators = enabledrequiresreportingtoregulators;
	}

	public Boolean getEnabledthirdpartycourse() {
		return this.enabledthirdpartycourse;
	}

	public void setEnabledthirdpartycourse(Boolean enabledthirdpartycourse) {
		this.enabledthirdpartycourse = enabledthirdpartycourse;
	}

	public Boolean getEnabledadditionalinforoncourseapproval() {
		return this.enabledadditionalinforoncourseapproval;
	}

	public void setEnabledadditionalinforoncourseapproval(
			Boolean enabledadditionalinforoncourseapproval) {
		this.enabledadditionalinforoncourseapproval = enabledadditionalinforoncourseapproval;
	}

	public Boolean getRatingTF() {
		return ratingTF;
	}

	public void setRatingTF(Boolean ratingTF) {
		this.ratingTF = ratingTF;
	}

	public BigDecimal getRating() {
		return rating;
	}

	public void setRating(BigDecimal rating) {
		this.rating = rating;
	}

	
	
	private String courseTypeName; 


	public String getCourseTypeName() {
		return courseTypeName;
	}

	public void setCourseTypeName(String courseTypeName) {
		this.courseTypeName = courseTypeName;
	}


	private String courseStatusRetired; 

	
	public String getCourseStatusRetired() {
		return courseStatusRetired;
	}

	public void setCourseStatusRetired(String courseStatusRetired) {
		this.courseStatusRetired = courseStatusRetired;
	}

	public String getLastModifiedDate() {
		return lastModifiedDate;
	}

	public void setLastModifiedDate(String lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

}
