//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.23 at 05:56:49 PM PKT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com/softech/vu360/lms/selfservice/webservices/orderservice", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.softech.vu360.lms.selfservice.webservices.orderservice;
